services:
  api:
    build:
      target: production
    environment:
      - NODE_ENV=production
    # Production-specific settings
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
