services:
  api:
    container_name: tas-api
    build:
      context: .
      target: ${BUILD_TARGET:-production}
      dockerfile: Dockerfile
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    volumes:
      - ${NODE_ENV:-production}-node_modules:/app/node_modules

volumes:
  production-node_modules:
  development-node_modules:
