services:
  api:
    build:
      target: development
    command: pnpm start:dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:delegated
      - development-node_modules:/app/node_modules
      - /app/dist
    # Enable debugging
    ports:
      - '${PORT:-3000}:3000'
      - '9229:9229' # Node.js debug port
